@"
spring.application.name=bookingsystem
spring.datasource.url=jdbc:mysql://localhost:3306/booking_system
spring.datasource.username=`${DB_USERNAME:root}
spring.datasource.password=`${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
jwt.secret=`${JWT_SECRET}
jwt.expiration=86400000
springdoc.swagger-ui.path=/swagger-ui.html
"@ | Set-Content src\main\resources\application.properties
